package com.lexyn.pixeldesign.logic.emitter;

import com.lexyn.pixeldesign.color.PixelColor;
import com.lexyn.pixeldesign.coord.PixelCoordinate;
import com.lexyn.pixeldesign.manager.ParticleSystemManager;

/***
 * A Particle is generated by an Emitter and represents exactly 1 pixel on the screen
 * @author lexyna
 */
public class Particle {

    private int x,y;
    private PixelColor color;

    private int lifetime;
    private int speed;

    public Particle(int x, int y, int lifetime, int speed, PixelColor color){
        this.x = x;
        this.y = y;
        this.lifetime = lifetime;
        this.speed = speed;
        this.color = color;
    }

    public void tick(){

        lifetime -= 1;
        x += speed;
        y += speed;

    }

    public void render(){
        ParticleSystemManager.getInstance().getActiveSystem().getPixelRenderer().renderPixel(new PixelCoordinate(x,y ), color);
    }

    public int getLifetime(){
        return lifetime;
    }

}
